CREATE TABLE school (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    title VARCHAR NOT NULL,
    chat_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    finished BOOLEAN NOT NULL DEFAULT FALSE
);