image: artifactory.devops.telekom.de/tvpp-docker/tvpp-runner:golang-1.16

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: devops_school_test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DATABASE_URL: postgres://localhost/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=disable

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in
    - /go/src/gitlab.devops.telekom.de

stages:
  - test
  - build

unit_tests:
  stage: test
  # TODO: https://github.com/golang/go/issues/44129 will be fixed in Go 1.17
  variables:
    GOFLAGS: "-mod=mod"
  script:
    - make test

build:
  stage: build
  script:
    - make