image: golang:1.17

services:
  - postgres:13.4-alpine

variables:
  POSTGRES_DB: devops_school_test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DATABASE_URL: postgres://postgres/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=disable

stages:
  - test
  - build
  - publish

before_script:
  - mkdir -p .go

test-bench:
  stage: test
  script:
    - make test-bench

test-verbose:
  stage: test
  script:
    - make test-verbose

test-race:
  stage: test
  script:
    - make test-race

test-coverage:
  stage: test
  script:
    - make test-coverage

build:
  stage: build
  script:
    - make build

publish:
  image: golang:1.17-alpine3.13
  services:
    - docker:dind
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  before_script:
    ## Create docker config
    - mkdir -p /root/.docker
    - echo "$DOCKER_CFG_FILE" > /root/.docker/config.json
    - apk update && apk add --no-cache git make docker-cli
  script:
    - make docker-release