image: artifactory.devops.telekom.de/tvpp-docker/tvpp-runner:golang-1.16

services:
  - postgres:12.2-alpine

variables:
  GOPATH: ${CI_PROJECT_DIR}/.go
  POSTGRES_DB: devops_school_test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DATABASE_URL: postgres://postgres/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=disable

cache:
  paths:
    - .go/pkg/mod/github.com/
    - .go/pkg/mod/golang.org/
    - .go/pkg/mod/google.golang.org/
    - .go/pkg/mod/gopkg.in/
    - .go/pkg/mod/gitlab.devops.telekom.de/

stages:
  - test
  - build

before_script:
  - mkdir -p .go

unit_tests:
  stage: test
  # TODO: https://github.com/golang/go/issues/44129 will be fixed in Go 1.17
  variables:
    GOFLAGS: "-mod=mod"
  script:
    - make test

code_coverage:
  stage: test
  script:
    - make coverage

build:
  stage: build
  script:
    - make all