image: artifactory.devops.telekom.de/tvpp-docker/tvpp-runner:golang-1.17

services:
  - postgres:12.2-alpine

variables:
  GOPATH: ${CI_PROJECT_DIR}/.go
  POSTGRES_DB: devops_school_test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DATABASE_URL: postgres://postgres/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=disable

cache:
  paths:
    - .go/pkg/mod/github.com/
    - .go/pkg/mod/golang.org/
    - .go/pkg/mod/google.golang.org/
    - .go/pkg/mod/gopkg.in/
    - .go/pkg/mod/gitlab.devops.telekom.de/

stages:
  - test
  - build
  - publish

before_script:
  - mkdir -p .go

test-bench:
  stage: test
  script:
    - make test-bench

test-verbose:
  stage: test
  script:
    - make test-verbose

test-race:
  stage: test
  script:
    - make test-race

test-coverage:
  stage: test
  script:
    - make test-coverage

build:
  stage: build
  script:
    - make all

publish:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  script:
    - docker build 
      --pull 
      -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}
      .
    - docker tag ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME} ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:latest
    - docker image push --all-tags ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}