version: '3.7'

services:
  postgres:
    image: postgres:13.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: devops_school
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - /pkg/devops-school-bot/db/postgresql/data:/var/lib/postgresql/data
  application:
    image: artifactory.devops.telekom.de/tvpp-docker/devops-school-bot:latest
    container_name: devops-school-bot
    restart: always
    volumes:
      - /pkg/devops-school-bot/configs:/app/configs
      - /pkg/devops-school-bot/db/migrations:/app/db/migrations
    entrypoint: ["/app/devops-school-bot", "start", "-c", "/app/configs/devopsschoolbot.toml"]
    depends_on:
      - postgres
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /pkg/devops-school-bot/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /pkg/devops-school-bot/nginx/.htpasswd:/etc/nginx/.htpasswd