version: '3.7'

services:
  postgres:
    image: postgres:13.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: devops_school
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - /pkg/devops-school-bot/db/postgresql/data:/var/lib/postgresql/data
  application:
    image: to4kin/devops-school-bot:latest
    container_name: devops-school-bot
    restart: always
    environment:
      DATABASE_URL: postgres://postgres/devops_school_dev?user=postgres&password=strongpassword&sslmode=disable
    depends_on:
      - postgres
