bind_addr = ":3000"
log_level = "debug"

[database]
url = "postgres://localhost/devops_school_dev?user=postgres&password=example&sslmode=disable"
migrations = "db/migrations"

[telegram_bot]
token = "1949550059:AAHQ3_ePCsQwfgV_w1FIGOCDG_fEvNiqMr8"
verbose = false
