bind_addr = ":3000"
log_level = "debug"
database_url = "postgres://localhost/devops_school_dev?user=postgres&password=example&sslmode=disable"

[telegram_bot]
token = "1745836330:AAEcNvnG6LCm9myT7pcSV-lguctxIeyq6nc"
verbose = true
