log_level: debug
debug_mode: true

apiserver:
  bind_addr: :3000

  cron:
    enabled: true
    fullreport: true
    schedule: "0 15 * * FRI"

awslambda:
  enabled: false

database:
  url: postgres://localhost/devops_school_dev?user=postgres&password=example&sslmode=disable
  migrations: db/migrations

telegram_bot:
  token: telegram-bot-token
  verbose: false
