package helper

import "errors"

var (
	// ErrInternal ...
	ErrInternal = errors.New("internal server error!\n\nsomething has gone wrong on the server")
	// ErrInsufficientPermissions ...
	ErrInsufficientPermissions = errors.New("you have insufficient permissions, please contact teachers or mentors")
	// ErrWrongChatType ...
	ErrWrongChatType = errors.New("wrong chat type, please use another chat for this command")
	// ErrSchoolNotStarted ...
	ErrSchoolNotStarted = errors.New("school not started, please contact teachers or mentors")
	// ErrReportNotFound ...
	ErrReportNotFound = errors.New("insufficient data for the report")
	// ErrUserNotJoined ...
	ErrUserNotJoined = errors.New("please join school first")
)
