name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.17
    needs: test
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build
        run: make all
